-- Seeder kategori contoh Potensi Desa Keseneng.
-- Jalankan setelah migration 006_create_potensi_desa.sql.
INSERT INTO potential_categories (
  id,
  slug,
  label,
  title,
  summary,
  image_url,
  accent_class_name,
  stat_value,
  stat_label,
  detail_eyebrow,
  detail_intro,
  detail_description,
  contact_name,
  contact_role,
  contact_email,
  display_order,
  is_active
) VALUES
(
  'b1c7c2dd-8f56-4b46-8d8a-8c1f701c0601',
  'pertanian',
  'Pertanian',
  'Pertanian pangan dan kebun produktif',
  'Sawah, kebun sayur, dan kelompok tani menjadi penggerak utama ekonomi warga sekaligus identitas Desa Keseneng.',
  'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85',
  'bg-sage-100 text-sage-800',
  '312 ha',
  'lahan produktif',
  'Potensi Pertanian',
  'Pertanian menjadi tulang punggung ekonomi lokal dengan lahan produktif, kelompok tani aktif, dan praktik kerja warga yang kuat.',
  'Pengembangan pertanian Desa Keseneng diarahkan pada peningkatan kualitas hasil pangan, penguatan kelembagaan kelompok tani, dan publikasi komoditas unggulan agar lebih mudah dikenali warga, mitra, dan pasar sekitar.',
  'Kelompok Tani Desa Keseneng',
  'Pengelola data pertanian',
  'pertanian@keseneng.desa.id',
  1,
  TRUE
),
(
  'b1c7c2dd-8f56-4b46-8d8a-8c1f701c0602',
  'kesenian',
  'Kesenian',
  'Kesenian warga dan tradisi desa',
  'Kelompok seni lokal menjaga ruang latihan, pentas tahunan, dan regenerasi anak muda agar tradisi desa tetap hidup.',
  'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=85',
  'bg-amber-100 text-amber-800',
  '5',
  'komunitas seni',
  'Potensi Kesenian',
  'Kesenian warga menjadi ruang ekspresi budaya sekaligus media regenerasi tradisi Desa Keseneng.',
  'Pengelolaan potensi kesenian diarahkan untuk mendokumentasikan kelompok seni, jadwal latihan, agenda pentas, dan cerita budaya agar identitas desa tampil lebih kuat di kanal digital.',
  'Komunitas Seni Keseneng',
  'Pengelola kegiatan budaya',
  'kesenian@keseneng.desa.id',
  2,
  TRUE
),
(
  'b1c7c2dd-8f56-4b46-8d8a-8c1f701c0603',
  'umkm',
  'UMKM',
  'Produk lokal dan usaha warga',
  'Olahan pangan, kerajinan, dan layanan warga disiapkan untuk memperluas pasar melalui publikasi digital desa.',
  'https://images.unsplash.com/photo-1605522561233-768ad7a8fabf?auto=format&fit=crop&w=1200&q=85',
  'bg-sky-100 text-sky-800',
  '48',
  'usaha warga',
  'Potensi UMKM',
  'UMKM warga menjadi pintu penguatan ekonomi lokal melalui produk pangan, kerajinan, dan layanan desa.',
  'Halaman detail UMKM disiapkan untuk menampung katalog produk, profil pelaku usaha, informasi kontak, dan cerita produksi agar produk lokal lebih mudah dipromosikan secara digital.',
  'Forum UMKM Desa Keseneng',
  'Pengelola data usaha warga',
  'umkm@keseneng.desa.id',
  3,
  TRUE
),
(
  'b1c7c2dd-8f56-4b46-8d8a-8c1f701c0604',
  'peternakan',
  'Peternakan',
  'Peternakan skala warga',
  'Ternak keluarga dan kelompok kecil menjadi penopang ekonomi tambahan yang terhubung dengan kebutuhan pangan lokal.',
  'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=1200&q=85',
  'bg-rose-100 text-rose-800',
  '9',
  'kelompok ternak',
  'Potensi Peternakan',
  'Peternakan warga mendukung ekonomi rumah tangga dan memperkuat siklus pangan lokal desa.',
  'Data peternakan disiapkan untuk mengenalkan kelompok ternak, jenis komoditas, kebutuhan pakan, dan peluang pengembangan usaha skala warga secara bertahap.',
  'Kelompok Ternak Keseneng',
  'Pengelola data peternakan',
  'peternakan@keseneng.desa.id',
  4,
  TRUE
)
ON DUPLICATE KEY UPDATE
  label = VALUES(label),
  title = VALUES(title),
  summary = VALUES(summary),
  image_url = VALUES(image_url),
  accent_class_name = VALUES(accent_class_name),
  stat_value = VALUES(stat_value),
  stat_label = VALUES(stat_label),
  detail_eyebrow = VALUES(detail_eyebrow),
  detail_intro = VALUES(detail_intro),
  detail_description = VALUES(detail_description),
  contact_name = VALUES(contact_name),
  contact_role = VALUES(contact_role),
  contact_email = VALUES(contact_email),
  display_order = VALUES(display_order),
  is_active = VALUES(is_active);

