UPDATE potential_categories SET status = 'archived', is_active = FALSE WHERE slug NOT IN ('wisata-alam', 'agro-tourism', 'umkm', 'seni-budaya');

INSERT INTO potential_categories (id, slug, label, title, summary, image_url, accent_class_name, stat_value, stat_label, detail_eyebrow, detail_intro, detail_description, contact_name, contact_role, contact_email, display_order, is_active, status, seo_title, seo_description, published_at) VALUES
('cfb6b648-f9cf-533b-983d-f0943c251d6a', 'wisata-alam', 'Wisata Alam', 'Wisata alam Desa Keseneng', 'Lanskap perbukitan, jalur jelajah, dan ruang alam desa menjadi daya tarik kunjungan yang dekat dengan kehidupan warga.', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', 'bg-emerald-100 text-emerald-800', '3', 'titik kunjungan', 'Potensi Wisata Alam', 'Wisata alam Keseneng menonjolkan suasana perbukitan, titik pandang, dan pengalaman kunjungan yang tetap dekat dengan desa.', 'Data wisata alam disiapkan untuk memuat nama lokasi, akses, dokumentasi visual, narahubung, dan catatan singkat yang bisa dilengkapi admin desa.', 'Pengelola Wisata Desa Keseneng', 'Pengelola data wisata alam', 'wisata@keseneng.desa.id', 1, TRUE, 'published', 'Wisata alam Desa Keseneng', 'Lanskap perbukitan, jalur jelajah, dan ruang alam desa menjadi daya tarik kunjungan yang dekat dengan kehidupan warga.', CURRENT_TIMESTAMP),
('c5a2c199-c01a-5c24-855c-094f98e9d5e8', 'agro-tourism', 'Agro Tourism', 'Agro tourism dan kebun produktif', 'Sawah, kebun, dan aktivitas tani warga dapat dikemas sebagai pengalaman edukasi pertanian dan kunjungan berbasis desa.', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85', 'bg-sage-100 text-sage-800', '312 ha', 'lahan produktif', 'Potensi Agro Tourism', 'Agro tourism menghubungkan aktivitas pertanian warga dengan pengalaman belajar, melihat proses tanam, dan mengenal komoditas desa.', 'Data agro tourism disiapkan untuk memuat lahan produktif, komoditas unggulan, kelompok tani, agenda panen, dan dokumentasi aktivitas yang bisa dilengkapi admin desa.', 'Kelompok Tani Desa Keseneng', 'Pengelola data agro tourism', 'agro@keseneng.desa.id', 2, TRUE, 'published', 'Agro tourism dan kebun produktif', 'Sawah, kebun, dan aktivitas tani warga dapat dikemas sebagai pengalaman edukasi pertanian dan kunjungan berbasis desa.', CURRENT_TIMESTAMP),
('850514ee-182d-5936-ac15-481bcb9e3463', 'umkm', 'UMKM', 'Produk lokal dan usaha warga', 'Olahan pangan, kerajinan, dan layanan warga disiapkan untuk memperluas pasar melalui publikasi digital desa.', 'https://images.unsplash.com/photo-1605522561233-768ad7a8fabf?auto=format&fit=crop&w=1200&q=85', 'bg-sky-100 text-sky-800', '48', 'usaha warga', 'Potensi UMKM', 'UMKM warga menjadi pintu penguatan ekonomi lokal melalui produk pangan, kerajinan, dan layanan desa.', 'Halaman detail UMKM disiapkan untuk menampung katalog produk, profil pelaku usaha, informasi kontak, dan cerita produksi agar produk lokal lebih mudah dipromosikan secara digital.', 'Forum UMKM Desa Keseneng', 'Pengelola data usaha warga', 'umkm@keseneng.desa.id', 3, TRUE, 'published', 'Produk lokal dan usaha warga', 'Olahan pangan, kerajinan, dan layanan warga disiapkan untuk memperluas pasar melalui publikasi digital desa.', CURRENT_TIMESTAMP),
('57d4e54e-ab88-56e0-8caf-f51a2c213699', 'seni-budaya', 'Seni & Budaya', 'Seni dan budaya Desa Keseneng', 'Jenis kesenian dan paguyuban aktif dikelola sebagai identitas budaya desa melalui dokumentasi yang mudah dibaca warga.', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=85', 'bg-amber-100 text-amber-800', '4', 'jenis seni', 'Potensi Seni & Budaya', 'Seni dan budaya warga menjadi ruang ekspresi, regenerasi tradisi, dan penguatan identitas Desa Keseneng.', 'Data seni budaya disiapkan untuk memuat jenis kesenian, kelompok aktif, jadwal latihan, agenda pentas, dan dokumentasi cerita budaya yang bisa dilengkapi admin desa.', 'Komunitas Seni Keseneng', 'Pengelola kegiatan budaya', 'budaya@keseneng.desa.id', 4, TRUE, 'published', 'Seni dan budaya Desa Keseneng', 'Jenis kesenian dan paguyuban aktif dikelola sebagai identitas budaya desa melalui dokumentasi yang mudah dibaca warga.', CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE label=VALUES(label), title=VALUES(title), summary=VALUES(summary), image_url=VALUES(image_url), accent_class_name=VALUES(accent_class_name), stat_value=VALUES(stat_value), stat_label=VALUES(stat_label), detail_eyebrow=VALUES(detail_eyebrow), detail_intro=VALUES(detail_intro), detail_description=VALUES(detail_description), contact_name=VALUES(contact_name), contact_role=VALUES(contact_role), contact_email=VALUES(contact_email), display_order=VALUES(display_order), is_active=VALUES(is_active), status=VALUES(status), seo_title=VALUES(seo_title), seo_description=VALUES(seo_description), published_at=VALUES(published_at);

DELETE FROM potential_highlights WHERE category_id IN ((SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), (SELECT id FROM potential_categories WHERE slug = 'umkm'), (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'));

DELETE FROM potential_opportunities WHERE category_id IN ((SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), (SELECT id FROM potential_categories WHERE slug = 'umkm'), (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'));

DELETE FROM potential_programs WHERE category_id IN ((SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), (SELECT id FROM potential_categories WHERE slug = 'umkm'), (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'));

DELETE FROM potential_gallery_items WHERE category_id IN ((SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), (SELECT id FROM potential_categories WHERE slug = 'umkm'), (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'));

INSERT INTO potential_highlights (id, category_id, label, display_order) VALUES
('4033a281-741a-5d29-b936-64b5061b9bfd', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), 'Perbukitan', 1),
('8752fef8-2e08-5a70-a082-d5161f83d274', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), 'Jalur jelajah', 2),
('9975a203-09f9-50e1-8989-a4e384c22653', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), 'Pemandangan', 3),
('34f9d8b2-f215-59b4-987c-4d3ea795e750', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), 'Sawah', 1),
('3b0529a7-9175-544a-bfa9-aa11f61d7a62', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), 'Kebun', 2),
('8d023f43-9a9c-5d63-b116-040c23663d4f', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), 'Edukasi tani', 3),
('8df20d4e-a82d-50ca-b321-ad338cce7146', (SELECT id FROM potential_categories WHERE slug = 'umkm'), 'Olahan pangan', 1),
('e6128d5e-c898-54ba-a45c-2f2e5583bb1b', (SELECT id FROM potential_categories WHERE slug = 'umkm'), 'Kerajinan', 2),
('0931ca89-3929-55ca-bd1f-02d340931757', (SELECT id FROM potential_categories WHERE slug = 'umkm'), 'Katalog digital', 3),
('6b5cd39c-4437-56ca-ab4b-d88827d5c6ee', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), 'Lengger', 1),
('782ecd9e-679c-58e1-bf1e-a6086687cefc', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), 'Jaran Kepang', 2),
('10fa6b52-d217-5641-87d5-fc0ebf66a915', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), 'Bundengan', 3);



INSERT INTO potential_gallery_items (id, category_id, potential_item_id, title, description, image_url, image_alt, display_order) VALUES
('2ea8a417-4047-5c4a-b984-28bb259a26a8', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), NULL, 'Lanskap perbukitan', 'Pemandangan alam desa yang menjadi daya tarik kunjungan.', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80', 'Lanskap perbukitan', 1),
('25e181ab-f789-5fee-9b32-ee8a4fb14975', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), NULL, 'Jalur jelajah desa', 'Rute alam yang menghubungkan ruang warga dan titik kunjungan.', 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80', 'Jalur jelajah desa', 2),
('a4e4a099-e09f-5427-89dd-0a9eb555b193', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), NULL, 'Ruang alam warga', 'Area terbuka desa yang didokumentasikan sebagai bagian dari potensi wisata.', 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=80', 'Ruang alam warga', 3),
('5b94d712-0ede-5b48-a078-bffb3b336962', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), NULL, 'Hamparan sawah produktif', 'Area pertanian warga yang menjadi bagian potensi agro tourism.', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80', 'Hamparan sawah produktif', 1),
('002623ee-9403-57f4-9506-2811ccc2d2b4', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), NULL, 'Pengelolaan kebun sayur', 'Kebun warga dikelola untuk kebutuhan harian, pasar lokal, dan edukasi.', 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=900&q=80', 'Pengelolaan kebun sayur', 2),
('8fef4b1b-5c19-531c-b43c-7af6d464578f', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), NULL, 'Panen bersama warga', 'Kegiatan panen menjadi ruang belajar dan kerja kolektif antarkeluarga.', 'https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?auto=format&fit=crop&w=900&q=80', 'Panen bersama warga', 3),
('f8822723-cbb7-549a-a131-ea72905fe3f8', (SELECT id FROM potential_categories WHERE slug = 'umkm'), NULL, 'Produk olahan pangan', 'Produk warga disiapkan untuk katalog dan kanal penjualan.', 'https://images.unsplash.com/photo-1605522561233-768ad7a8fabf?auto=format&fit=crop&w=900&q=80', 'Produk olahan pangan', 1),
('1d2105a8-eed0-5739-9686-62ad03b94c44', (SELECT id FROM potential_categories WHERE slug = 'umkm'), NULL, 'Kemasan produk lokal', 'Kemasan produk lokal menjadi bagian dari identitas usaha warga.', 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=900&q=80', 'Kemasan produk lokal', 2),
('bf5c0f65-1697-54df-a254-b5dc12c24c45', (SELECT id FROM potential_categories WHERE slug = 'umkm'), NULL, 'Etalase usaha warga', 'Ragam usaha kecil menjadi bagian penting ekonomi desa.', 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80', 'Etalase usaha warga', 3),
('fb46ea6c-cfe7-5dc6-99b7-662f624803fb', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), NULL, 'Latihan seni warga', 'Ruang latihan menjadi tempat regenerasi kelompok seni desa.', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=900&q=80', 'Latihan seni warga', 1),
('13facbb3-20c1-5ac3-8c49-4754f8c3ade6', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), NULL, 'Pentas budaya tahunan', 'Panggung desa menghubungkan tradisi dengan generasi muda.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80', 'Pentas budaya tahunan', 2),
('803c99df-f4ab-5e6c-a983-551dce8d963d', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), NULL, 'Dokumentasi tradisi', 'Arsip visual disiapkan untuk mengenalkan identitas budaya.', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80', 'Dokumentasi tradisi', 3);

INSERT INTO potential_items (id, category_id, title, slug, summary, description, image_url, image_alt, status, published_at, display_order, seo_title, seo_description) VALUES
('b0ed064b-a1f5-5a0d-a592-8b5646cb0054', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), 'Lanskap perbukitan', 'wisata-alam-1', 'Pemandangan alam desa yang menjadi daya tarik kunjungan.', 'Pemandangan alam desa yang menjadi daya tarik kunjungan.', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80', 'Lanskap perbukitan', 'published', '2026-07-10 00:00:00', 1, 'Lanskap perbukitan', 'Pemandangan alam desa yang menjadi daya tarik kunjungan.'),
('7f1fa1a9-aa3c-5c42-b719-c805357889da', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), 'Jalur jelajah desa', 'wisata-alam-2', 'Rute alam yang menghubungkan ruang warga dan titik kunjungan.', 'Rute alam yang menghubungkan ruang warga dan titik kunjungan.', 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80', 'Jalur jelajah desa', 'published', '2026-07-10 00:00:00', 2, 'Jalur jelajah desa', 'Rute alam yang menghubungkan ruang warga dan titik kunjungan.'),
('d7eb5526-9ffd-5b7d-a752-8c5b3f27cae9', (SELECT id FROM potential_categories WHERE slug = 'wisata-alam'), 'Ruang alam warga', 'wisata-alam-3', 'Area terbuka desa yang didokumentasikan sebagai bagian dari potensi wisata.', 'Area terbuka desa yang didokumentasikan sebagai bagian dari potensi wisata.', 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=80', 'Ruang alam warga', 'draft', NULL, 3, 'Ruang alam warga', 'Area terbuka desa yang didokumentasikan sebagai bagian dari potensi wisata.'),
('c5eb62eb-afde-557f-a304-9c566f71dd73', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), 'Hamparan sawah produktif', 'agro-tourism-1', 'Area pertanian warga yang menjadi bagian potensi agro tourism.', 'Area pertanian warga yang menjadi bagian potensi agro tourism.', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=80', 'Hamparan sawah produktif', 'published', '2026-07-10 00:00:00', 4, 'Hamparan sawah produktif', 'Area pertanian warga yang menjadi bagian potensi agro tourism.'),
('bbf4dab4-cd18-5993-b356-de741a093247', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), 'Pengelolaan kebun sayur', 'agro-tourism-2', 'Kebun warga dikelola untuk kebutuhan harian, pasar lokal, dan edukasi.', 'Kebun warga dikelola untuk kebutuhan harian, pasar lokal, dan edukasi.', 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=900&q=80', 'Pengelolaan kebun sayur', 'published', '2026-07-10 00:00:00', 5, 'Pengelolaan kebun sayur', 'Kebun warga dikelola untuk kebutuhan harian, pasar lokal, dan edukasi.'),
('eba0b386-c34f-5da1-954d-a5fb17a368a3', (SELECT id FROM potential_categories WHERE slug = 'agro-tourism'), 'Panen bersama warga', 'agro-tourism-3', 'Kegiatan panen menjadi ruang belajar dan kerja kolektif antarkeluarga.', 'Kegiatan panen menjadi ruang belajar dan kerja kolektif antarkeluarga.', 'https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?auto=format&fit=crop&w=900&q=80', 'Panen bersama warga', 'draft', NULL, 6, 'Panen bersama warga', 'Kegiatan panen menjadi ruang belajar dan kerja kolektif antarkeluarga.'),
('36f11a66-b395-564b-bbfe-34a0f9aad145', (SELECT id FROM potential_categories WHERE slug = 'umkm'), 'Produk olahan pangan', 'umkm-1', 'Produk warga disiapkan untuk katalog dan kanal penjualan.', 'Produk warga disiapkan untuk katalog dan kanal penjualan.', 'https://images.unsplash.com/photo-1605522561233-768ad7a8fabf?auto=format&fit=crop&w=900&q=80', 'Produk olahan pangan', 'published', '2026-07-10 00:00:00', 7, 'Produk olahan pangan', 'Produk warga disiapkan untuk katalog dan kanal penjualan.'),
('e8250aa7-eab5-5eae-af71-be9c53847430', (SELECT id FROM potential_categories WHERE slug = 'umkm'), 'Kemasan produk lokal', 'umkm-2', 'Kemasan produk lokal menjadi bagian dari identitas usaha warga.', 'Kemasan produk lokal menjadi bagian dari identitas usaha warga.', 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=900&q=80', 'Kemasan produk lokal', 'published', '2026-07-10 00:00:00', 8, 'Kemasan produk lokal', 'Kemasan produk lokal menjadi bagian dari identitas usaha warga.'),
('6cd39aaf-ad19-514a-a4ba-c0bbfbe38f94', (SELECT id FROM potential_categories WHERE slug = 'umkm'), 'Etalase usaha warga', 'umkm-3', 'Ragam usaha kecil menjadi bagian penting ekonomi desa.', 'Ragam usaha kecil menjadi bagian penting ekonomi desa.', 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=900&q=80', 'Etalase usaha warga', 'draft', NULL, 9, 'Etalase usaha warga', 'Ragam usaha kecil menjadi bagian penting ekonomi desa.'),
('dba5db20-73a5-54fc-8a4f-3f7ef5dcaca7', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), 'Latihan seni warga', 'seni-budaya-1', 'Ruang latihan menjadi tempat regenerasi kelompok seni desa.', 'Ruang latihan menjadi tempat regenerasi kelompok seni desa.', 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=900&q=80', 'Latihan seni warga', 'published', '2026-07-10 00:00:00', 10, 'Latihan seni warga', 'Ruang latihan menjadi tempat regenerasi kelompok seni desa.'),
('979df5d1-9b39-5ea8-b9d0-4356cd260dff', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), 'Pentas budaya tahunan', 'seni-budaya-2', 'Panggung desa menghubungkan tradisi dengan generasi muda.', 'Panggung desa menghubungkan tradisi dengan generasi muda.', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80', 'Pentas budaya tahunan', 'published', '2026-07-10 00:00:00', 11, 'Pentas budaya tahunan', 'Panggung desa menghubungkan tradisi dengan generasi muda.'),
('f5f35529-729d-51e4-b995-b2f8f54e7412', (SELECT id FROM potential_categories WHERE slug = 'seni-budaya'), 'Dokumentasi tradisi', 'seni-budaya-3', 'Arsip visual disiapkan untuk mengenalkan identitas budaya.', 'Arsip visual disiapkan untuk mengenalkan identitas budaya.', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80', 'Dokumentasi tradisi', 'draft', NULL, 12, 'Dokumentasi tradisi', 'Arsip visual disiapkan untuk mengenalkan identitas budaya.')
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), title=VALUES(title), summary=VALUES(summary), description=VALUES(description), image_url=VALUES(image_url), image_alt=VALUES(image_alt), status=VALUES(status), published_at=VALUES(published_at), display_order=VALUES(display_order), seo_title=VALUES(seo_title), seo_description=VALUES(seo_description);
